openapi: 3.1.0
info:
  title: API
  description: |
    # REST API
servers:
  - url: http://localhost:3000/api
paths:
  /profile:
    get:
      tags:
        - Інформація про користувача
      summary: GET
      operationId: get_sysStatus
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Шавченко ірина миколаївна
                  phone:
                    type: string
                    format: date
                    example: "4567"
                  email:
                    type: string
                    example: forexsample@gmail.com
                  telegram:
                    type: string
                    example: forexample
                  university:
                    type: string
                    example: ККБАД
                  course:
                    type: string
                    example: "3"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-swagger-router-controller: SystemOPS
  /orders:
    get:
      tags:
        - Замовлення
      summary: GET
      operationId: get_sysStatus
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: Розмноження савці в умовах когнітивної кризи
                        status:
                          type: boolean
                          example: true
                        type:
                          type: string
                          example: Реферат
                        object:
                          type: string
                          example: Біологія
                        deadline:
                          type: string
                          example: 11.02.2023
                        id:
                          type: string
                          example: 4058-245
                        price:
                          type: string
                          example: "455"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-swagger-router-controller: SystemOPS
  /faq:
    get:
      tags:
        - FAQ
      summary: GET
      operationId: get_sysStatus
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "1"
                        title:
                          type: string
                          example: Як зробити замовлення?
                        text:
                          type: string
                          example:
                            Ви можете зареєструватись на замовити роботу на сайті або в менеджера
                            через Instagram чи Telegram, як вам зручно.

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-swagger-router-controller: SystemOPS
  /order:
    post:
      tags:
        - Нове замовлення
      summary: POST
      operationId: get_sysStatus
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  worktype:
                    type: string
                    example: lesson1
                  deadline:
                    type: string
                    example: lesson1
                  lesson:
                    type: string
                    example: lesson1
                  warranty:
                    type: string
                    example: lesson1
                  count:
                    type: string
                    example: "32"
                  theme:
                    type: string
                    example: Тест
                  contact:
                    type: string
                    format: date-time
                    example: "232345"
                  uniq:
                    type: string
                    example: ""
                  note:
                    type: string
                    example: тест тест
                  agree:
                    type: boolean
                    example: true
                  files:
                    type: array
                    items:
                      type: string
                      format: nullable

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-swagger-router-controller: SystemOPS
