openapi: 3.1.0
info:
  title: API
  description: |
    # REST API
servers:
  - url: http://localhost:3000/api
paths:
  /profile:
    get:
      tags:
        - Інформація про користувача
      summary: GET
      operationId: get_sysStatus
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Шавченко ірина миколаївна
                  phone:
                    type: string
                    format: date
                    example: "4567"
                  email:
                    type: string
                    example: forexsample@gmail.com
                  telegram:
                    type: string
                    example: forexample
                  university:
                    type: string
                    example: ККБАД
                  course:
                    type: string
                    example: "3"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-swagger-router-controller: SystemOPS
  /orders:
    get:
      tags:
        - Замовлення
      summary: GET
      operationId: get_sysStatus
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: Розмноження савці в умовах когнітивної кризи
                        status:
                          type: boolean
                          example: true
                        type:
                          type: string
                          example: Реферат
                        object:
                          type: string
                          example: Біологія
                        deadline:
                          type: string
                          example: 11.02.2023
                        id:
                          type: string
                          example: 4058-245
                        price:
                          type: string
                          example: "455"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-swagger-router-controller: SystemOPS
